---
title: "Dplyr"
format: revealjs
---

## Summary

- Pipe
- Row dplyr functions
- Column dplyr functions


# Warm up {background-color="#e8e8e8"}

## R learning curve

```{r}
library(dplyr)
rlc <- tibble(class = 1:8,
             knowledge = (1:8)^3)
class <- 4
plot(rlc$class, rlc$knowledge)
points(rlc$class[class], rlc$knowledge[class], col = "red")
```

# Pipe {background-color="#e8e8e8"}

## Pipe

One function
```{r eval = F, echo = TRUE}
f(d$v)
f(d, v)
d |> f(v)
1:100 |> 
   sample(4)
```

Various functions
```{r eval = F, echo = TRUE}
f1(f1(d, v1), v2)
d |> 
  f1(v1) |> 
  f2(v2)
```



## Pipe

Without pipe
```{r eval = F, echo = TRUE}
go_to_upf(take_transport(get_dressed(get_out_of_bed(wake_up(me,
time = "8:30"), side = "left"), pants = TRUE, shirt = TRUE), 
bus = TRUE, metro = FALSE), mqi = FALSE, bar = TRUE)
```

With pipe

```{r eval = F, echo = TRUE}
me |> 
  wake_up(time = "8:30") |> 
  get_out_of_bed(side = "left") |> 
  get_dressed(pants = TRUE, shirt = TRUE) |> 
  take_transport(bus = TRUE, metro = FALSE) |> 
  go_to_upf(mqi = FALSE, bar = TRUE)
```

Example taken from [here](https://twitter.com/hadleywickham/status/1359852563726819332?s=20&t=J8qesZb3u9EAwVKMYMgh1Q) and [here](https://evalsp21.classes.andrewheiss.com/projects/01_lab/slides/01_lab.html#116).



# Row dplyr functions

## Filter



## Arrange




# Columns

## Mutate


## Select

## Rename


## Relocate


# Groups

## Group_by



## Summarize

















