install.packages("gapminder")
library(pacman)
p_load(tidyverse, gapminder)
write_csv(gapminder, "gapminder.csv")
write_csv2(gapminder, "gapminder2.csv")
write_tsv(gapminder, "gapminder3.tsv")
write_delim(gapminder, "gapminder4.txt", delim = "/")
